apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  #git repo
  source: 
    repoURL: https://github.com/nitin-aristocrat/argocd-testapp.git
    targetRevision: HEAD
    path: dev
  #k8s cluster info
  destination:
    server: https://kubernetes.default.svc
    namespace: dev 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true